# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x08\x42ookgrpc\x1a\x1bgoogle/protobuf/empty.proto\"R\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tbook_name\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\r\n\x05pages\x18\x04 \x01(\x05\x12\x0c\n\x04rate\x18\x05 \x01(\t\"\x11\n\x0f\x42ookListRequest\"!\n\x13\x42ookRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xdc\x01\n\x0e\x42ookController\x12\x35\n\x04List\x12\x19.Bookgrpc.BookListRequest\x1a\x0e.Bookgrpc.Book\"\x00\x30\x01\x12*\n\x06\x43reate\x12\x0e.Bookgrpc.Book\x1a\x0e.Bookgrpc.Book\"\x00\x12;\n\x08Retrieve\x12\x1d.Bookgrpc.BookRetrieveRequest\x1a\x0e.Bookgrpc.Book\"\x00\x12*\n\x06Update\x12\x0e.Bookgrpc.Book\x1a\x0e.Bookgrpc.Book\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=53
  _BOOK._serialized_end=135
  _BOOKLISTREQUEST._serialized_start=137
  _BOOKLISTREQUEST._serialized_end=154
  _BOOKRETRIEVEREQUEST._serialized_start=156
  _BOOKRETRIEVEREQUEST._serialized_end=189
  _BOOKCONTROLLER._serialized_start=192
  _BOOKCONTROLLER._serialized_end=412
# @@protoc_insertion_point(module_scope)
