# Generated by Django 4.1.4 on 2022-12-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True)),
                ('death_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('pages', models.CharField(max_length=100)),
                ('rate', models.CharField(choices=[('G', 'good'), ('M', 'medium'), ('B', 'bad'), ('NR', 'not rated')], default='NR', max_length=100)),
            ],
        ),
    ]
